import Navbar from '../components/navbar'
import Head from 'next/head'
import '../styles/globals.css'

function MyApp({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Cody H. | Web Dev</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="../favicon.png" />
      </Head>
      
      <Navbar />
      <Component {...pageProps} />
    </>
  )
}

export default MyApp
