import Head from 'next/head'
import Image from 'next/image'
import About from '../components/about'
import Contact from '../components/contact'
import Main from '../components/main'
import Navbar from '../components/navbar'
import Projects from '../components/projects'
import Skills from '../components/skills'


export default function Home() {
  return (
    <div>
      <Head>
        <title>Cody H. | Web Dev</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/assets/Logo" />
      </Head>

      <Main />
      <Navbar />
      <About />
      <Skills />
      <Projects />
      <Contact />
        
            
    </div>
  )
}
